"use client";
import { useRef, useState, type KeyboardEvent } from 'react';
import { Wheat, Heart, MessageCircle, Crown, Cookie, Croissant, CookingPot, Cherry, X, Plus, Minus, ShoppingBag, Trash2, Camera, Users } from 'lucide-react';
const whatsapp=(product?:string)=>`https://wa.me/5531986398494?text=${encodeURIComponent(product?`Olá, Pães Catarina! Gostaria de encomendar: ${product}.`:'Olá, Pães Catarina! Gostaria de fazer uma encomenda.')}`;
const photos={bread:'/images/catalogo-1.jpg',salted:'/images/pao-forma-salgado.webp',whole:'/images/pao-forma-integral.webp',sweet:'/images/catalogo-4.jpg',rolls:'/images/catalogo-5.jpg',cake:'/images/catalogo-6.jpg',pie:'/images/catalogo-7.jpg',jam:'/images/catalogo-8.jpg'};
type Product={name:string;short:string;description:string;image:string;tag:string;options?:string[]};
const families:{name:string;icon:typeof Wheat;title:string;description:string;products:Product[]}[]=[
{name:'Pães',icon:Wheat,title:'Um carinho em cada fatia.',description:'Do clássico pão caseiro aos recheios que abraçam. Escolha o seu favorito.',products:[
{name:'Pão caseiro de massa doce sem recheio',short:'Caseiro de massa doce',description:'Massa macia, levemente adocicada e sem recheio. Um convite para passar o café e aproveitar sem pressa.',image:photos.bread,tag:'O clássico de casa'},
{name:'Pão caseiro de massa salgada sem recheio',short:'Caseiro de massa salgada',description:'Pão caseiro de massa salgada, fofinho e sem recheio. Simples e acolhedor para acompanhar a sua mesa.',image:photos.salted,tag:'Para todos os dias'},
{name:'Pão 100% integral',short:'Pão 100% integral',description:'O sabor marcante do pão integral em uma versão caseira, para saborear fatia por fatia.',image:photos.whole,tag:'Sabor integral'},
{name:'Pão doce recheado',short:'Pão doce recheado',description:'Massa doce e macia com um recheio especial. Escolha entre o sabor da goiabada e a cremosidade do doce de leite.',image:photos.sweet,tag:'Dois jeitos de amar',options:['Goiabada','Doce de leite']},
{name:'Pão de forma recheado com frango',short:'Pão recheado com frango',description:'Pão caseiro tipo de forma, com massa macia e recheio de frango. Uma fatia generosa com gostinho de comida feita em casa.',image:'/images/pao-forma-frango.jpg',tag:'Recheado de afeto'},
{name:'Pão de forma recheado com presunto e mussarela',short:'Pão com presunto e mussarela',description:'Pão caseiro tipo de forma, recheado com presunto e mussarela. Massa fofinha e recheio em cada fatia para um lanche especial.',image:'/images/pao-forma-presunto-mussarela.jpg',tag:'Uma fatia de carinho'}]},
{name:'Cucas Alemãs',icon:Cookie,title:'Tradição que dá vontade de repetir.',description:'Massa delicada, recheios especiais e a irresistível farofa crocante por cima.',products:[
{name:'Cuca alemã de Banana',short:'Cuca alemã de banana',description:'Banana, massa macia e a tradicional farofa streusel. Uma combinação que tem sabor de café da tarde.',image:photos.cake,tag:'Tradição do Sul'},
{name:'Cuca alemã de Goiabada',short:'Cuca alemã de goiabada',description:'A doçura da goiabada sob uma cobertura de farofa crocante, com todo o encanto da cuca alemã.',image:'/images/cuca-goiabada.jpg',tag:'Doce encontro'},
{name:'Cuca alemã de Doce de leite',short:'Cuca alemã de doce de leite',description:'Recheio de doce de leite e a farofinha dourada que faz cada pedaço ser especial.',image:'/images/cuca-doce-leite-v2.jpg',tag:'Para saborear devagar'}]},
{name:'Enrolados',icon:Croissant,title:'Douradinhos por fora. Afeto por dentro.',description:'Massa macia e combinações de recheios para deixar o lanche ainda mais gostoso.',products:[
{name:'Enrolado de presunto com queijo',short:'Presunto com queijo',description:'O encontro clássico de presunto e queijo, envolvido em uma massa macia e douradinha.',image:photos.rolls,tag:'Combinação clássica'},
{name:'Enrolado de frango com queijo',short:'Frango com queijo',description:'Recheio de frango com queijo em um enrolado caseiro, feito para acompanhar uma boa pausa.',image:'/images/enrolado-frango-queijo-v2.jpg',tag:'Lanche com carinho'},
{name:'Enrolado de carne com queijo',short:'Carne com queijo',description:'Carne e queijo em uma massa dourada. Uma combinação cheia de sabor para o seu lanche.',image:'/images/enrolado-carne-queijo-v2.jpg',tag:'Sabor de casa'}]},
{name:'Empadão',icon:CookingPot,title:'Para dividir à mesa.',description:'Uma receita acolhedora, da primeira casquinha ao último pedacinho.',products:[
{name:'Empadão de frango',short:'Empadão de frango',description:'Massa delicada e quebradiça com recheio cremoso de frango. Perfeito para reunir quem você ama à mesa.',image:photos.pie,tag:'Feito para compartilhar'}]},
{name:'Geleias',icon:Cherry,title:'Pequenos potes de felicidade.',description:'O toque de fruta que transforma uma fatia de pão em um momento especial.',products:[
{name:'Geleia de morango',short:'Geleia de morango',description:'Cor viva e sabor de morango para acompanhar pães, torradas e os seus melhores cafés da manhã.',image:photos.jam,tag:'Doçura em cada colher'},
{name:'Geleia de uva',short:'Geleia de uva',description:'O sabor intenso da uva em uma geleia caseira. Uma companhia especial para o seu pão favorito.',image:'/images/catalogo-9.jpg',tag:'Sabor de fruta'}]}
];
type CartItem={name:string;quantity:number;image:string};
function differences(product:Product){
if(product.name==='Pão 100% integral')return ['Farinha 100% integral selecionada.','Duas colherinhas de açúcar mascavo por receita.','Óleo de canola ou girassol.'];
if(product.name.startsWith('Pão'))return ['Farinha especial de qualidade premium.','Óleo de canola ou girassol.','Preparo artesanal e massa caseira.'];
if(product.name.startsWith('Cuca'))return ['Cobertura tradicional de farofa streusel.','Preparo artesanal com o recheio escolhido.'];
if(product.name.startsWith('Enrolado'))return ['Massa caseira dourada no forno.','Recheio combinado com queijo.'];
if(product.name.startsWith('Empadão'))return ['Massa delicada e quebradiça.','Recheio cremoso de frango.'];
return ['Receita caseira com sabor de fruta.','Uma companhia para pães e torradas.'];
}
export default function Home(){
const [cart,setCart]=useState<CartItem[]>([]);const [notice,setNotice]=useState('');const cartDialog=useRef<HTMLDialogElement>(null);
const count=cart.reduce((sum,item)=>sum+item.quantity,0);
const orderText='Olá, Pães Catarina! Gostaria de encomendar:\n\n'+cart.map(item=>item.quantity+' × '+item.name).join('\n')+'\n\nPodem confirmar os valores, a disponibilidade e a entrega ou retirada?';
const orderUrl='https://wa.me/5531986398494?text='+encodeURIComponent(orderText);
function add(product:Product,option=''){
const name=product.name+(option?' — '+option:'');
setCart(items=>{const found=items.find(item=>item.name===name);return found?items.map(item=>item.name===name?{...item,quantity:item.quantity+1}:item):[...items,{name,quantity:1,image:product.image}]});
setNotice(name+' adicionado ao carrinho.');
}
function changeQuantity(name:string,amount:number){setCart(items=>items.map(item=>item.name===name?{...item,quantity:item.quantity+amount}:item).filter(item=>item.quantity>0));}

const [active,setActive]=useState(0);const [selected,setSelected]=useState<Product|null>(null);const [flavor,setFlavor]=useState('');const dialog=useRef<HTMLDialogElement>(null);const opener=useRef<HTMLButtonElement|null>(null);const family=families[active];
function openProduct(product:Product,button:HTMLButtonElement){opener.current=button;setSelected(product);setFlavor(product.options?.[0]??'');dialog.current?.showModal();}
function handleTabs(event:KeyboardEvent<HTMLButtonElement>,index:number){let next=index;if(event.key==='ArrowRight')next=(index+1)%families.length;else if(event.key==='ArrowLeft')next=(index+families.length-1)%families.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=families.length-1;else return;event.preventDefault();setActive(next);document.getElementById(`tab-${next}`)?.focus();}
return <><a className="skip-link" href="#catalogo">Ir para o cardápio</a><header className="site-header"><div className="header-main wrap flex items-center justify-between gap-4"><a href="#" aria-label="Pães Catarina — início" className="brand flex items-center gap-3"><span className="brand-emblem"><Wheat size={28} strokeWidth={1.3}/></span><span><span className="brand-name">Pães Catarina</span><span className="brand-caption">ARTESANAL · CASEIRO · COM AFETO</span></span></a><button type="button" className="cart-toggle" onClick={()=>cartDialog.current?.showModal()} aria-label={`Abrir carrinho, ${count} itens`}><ShoppingBag size={20}/><span>Carrinho</span><b>{count}</b></button><a className="header-contact" href={count?orderUrl:whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/><span>Faça sua encomenda</span></a></div><nav className="tabs-wrap" aria-label="Famílias de produtos"><div className="tabs wrap" role="tablist" aria-label="Cardápio">{families.map((category,index)=><button key={category.name} type="button" role="tab" id={`tab-${index}`} aria-controls="catalogo" aria-selected={active===index} tabIndex={active===index?0:-1} onKeyDown={e=>handleTabs(e,index)} onClick={()=>setActive(index)}><category.icon size={19} strokeWidth={1.5}/>{category.name}<span className="tab-count">0{category.products.length}</span></button>)}</div></nav></header>
<main><section className="welcome wrap" aria-label="Bem-vindo à Pães Catarina"><div className="welcome-copy"><div className="eyebrow"><span/>RECEITAS QUE ACOLHEM</div><h1>Tem cheiro de pão.<br/>Tem <em>gosto de casa.</em></h1><p>O carinho de fazer à mão.<br/>A tradição do Sul em cada fatia.</p><div className="welcome-sign"><Heart size={17} strokeWidth={1.5}/><span>Feito em casa, feito com amor.</span></div></div><div className="welcome-art"><img src="/images/catarina.png" alt="Ilustração da Catarina em uma cozinha rústica, com pães e forno a lenha" fetchPriority="high"/><span className="art-caption">BEM-VINDO À NOSSA COZINHA</span></div></section>
<section id="catalogo" className="catalog wrap" role="tabpanel" aria-labelledby={`tab-${active}`} tabIndex={0}><div className="section-heading"><div><div className="eyebrow">NOSSO CARDÁPIO <span className="tiny-divider"/>{family.name.toLocaleUpperCase('pt-BR')}</div><h2>{family.title}</h2><p>{family.description}</p></div><span className="handmade"><Wheat size={26} strokeWidth={1}/><span>Com tempo.<br/>Com carinho.</span></span></div><div key={active} className={`product-grid ${family.products.length===1?'single-product':''}`}>{family.products.map((product,index)=><article className="product-card" key={product.name}><div className="product-photo"><img src={product.image} alt={`Imagem ilustrativa de ${product.name.toLocaleLowerCase('pt-BR')}`} loading={index<3?'eager':'lazy'} onError={e=>{e.currentTarget.style.display='none';}}/><span className="photo-fallback"><Wheat size={46} strokeWidth={1}/><span>{product.short}</span></span><span className="product-label">{product.tag}</span><button type="button" className="photo-action" aria-label={`Adicionar ao carrinho: ${product.name}`} onClick={event=>product.options?openProduct(product,event.currentTarget):add(product)}><Plus size={20}/><span>Adicionar</span></button></div><div className="product-body"><span className="product-number">{String(index+1).padStart(2,'0')} / {family.name}</span><h3>{product.short}</h3><p>{product.description}</p>{product.options&&<span className="flavors">Goiabada <span>ou</span> Doce de leite</span>}<button type="button" className="card-link" onClick={event=>openProduct(product,event.currentTarget)}>Ingredientes e diferenciais <Plus size={16}/></button></div></article>)}</div><p className="image-note">Imagens ilustrativas. Cada fornada tem seu próprio encanto.</p></section>
</main>
<footer className="footer"><div className="wrap footer-content"><div><span className="footer-brand"><Crown size={20} strokeWidth={1.4}/> Pães Catarina</span><p>O sabor de casa. O carinho de sempre.</p></div><div className="socials"><span>REDES SOCIAIS · EM BREVE</span><div><a href="https://www.instagram.com/" aria-label="Instagram — link ilustrativo" target="_blank" rel="noopener noreferrer"><Camera size={20}/></a><a href="https://www.facebook.com/" aria-label="Facebook — link ilustrativo" target="_blank" rel="noopener noreferrer"><Users size={20}/></a></div></div></div><div className="wrap footer-bottom"><span>© Pães Catarina · Feito com afeto.</span><span>Da nossa família para a sua.</span></div></footer>
<a className="floating-whatsapp" href={count?orderUrl:whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={23}/><span>Encomende pelo WhatsApp</span></a>
<dialog ref={dialog} className="product-dialog" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}} onClose={()=>{opener.current?.focus();}} aria-labelledby="product-title">{selected&&<div className="dialog-content"><button type="button" className="close-dialog" onClick={()=>dialog.current?.close()} aria-label="Fechar detalhes"><X size={22}/></button><img className="dialog-photo" src={selected.image} alt={`Imagem ilustrativa: ${selected.name}`}/><div className="dialog-text"><div className="eyebrow">FEITO COM CARINHO</div><h2 id="product-title">{selected.name}</h2><ul className="differences">{differences(selected).map(detail=><li key={detail}>{detail}</li>)}</ul>{selected.options&&<fieldset><legend>Escolha o seu recheio</legend><div className="flavor-options">{selected.options.map(option=><label key={option}><input type="radio" name="flavor" value={option} checked={flavor===option} onChange={()=>setFlavor(option)}/><span>{option}</span></label>)}</div></fieldset>}<button type="button" className="button" onClick={()=>{add(selected,flavor);dialog.current?.close();}}><Plus size={19}/>Adicionar ao carrinho</button><small>Imagem ilustrativa. Consulte a disponibilidade pelo WhatsApp.</small></div></div>}</dialog>
<p role="status" className="cart-notice">{notice}</p>
<dialog ref={cartDialog} className="cart-dialog" aria-labelledby="cart-title" onClick={e=>{if(e.target===e.currentTarget)cartDialog.current?.close();}}>
<div className="cart-heading"><div><span className="eyebrow">SUA ENCOMENDA</span><h2 id="cart-title">Seu carrinho</h2></div><button type="button" aria-label="Fechar carrinho" onClick={()=>cartDialog.current?.close()}><X/></button></div>
{cart.length===0?<div className="empty-cart"><ShoppingBag size={40}/><p>Seu carrinho está esperando um carinho.</p><button type="button" className="button" onClick={()=>cartDialog.current?.close()}>Escolher produtos</button></div>:<>
<ul className="cart-items">{cart.map(item=><li key={item.name}><img src={item.image} alt=""/><div className="cart-item-info"><h3>{item.name}</h3><div className="quantity-control"><button type="button" aria-label={`Diminuir quantidade de ${item.name}`} onClick={()=>changeQuantity(item.name,-1)}><Minus size={16}/></button><span aria-label="Quantidade">{item.quantity}</span><button type="button" aria-label={`Aumentar quantidade de ${item.name}`} onClick={()=>changeQuantity(item.name,1)}><Plus size={16}/></button><button type="button" aria-label={`Remover ${item.name}`} onClick={()=>setCart(items=>items.filter(i=>i.name!==item.name))}><Trash2 size={17}/></button></div></div></li>)}</ul>
<div className="cart-checkout"><p>{count} {count===1?'item selecionado':'itens selecionados'}</p><a className="button" href={orderUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>Enviar encomenda pelo WhatsApp</a><small>A lista será aberta no WhatsApp para você enviar. Valores, disponibilidade e pagamento são combinados por lá.</small><button type="button" className="continue-shopping" onClick={()=>cartDialog.current?.close()}>Continuar escolhendo</button></div></>}
</dialog></>;
}




